const CALL_GENERATION_INTERVAL = 3000;
const PENDING_CALLS_INTERVAL = 5000;
const DISPATCH_TIMEOUT = 16000;
const TOTAL_SIMULATION_TIME = 10000;

module.exports = {
  CALL_GENERATION_INTERVAL,
  PENDING_CALLS_INTERVAL,
  DISPATCH_TIMEOUT,
  TOTAL_SIMULATION_TIME,
};
